### ISSUE TITLE
temporal blocks vs fixed dates

### ISSUE THREAD

**Issue by topographos** [tesselle/kairos#1]
Hi,
Many thanks for a great package. I have been learning aoristic analysis comparing R packages and have noticed a different implementation of the method. It seems that _kairos_  and _aoristAAR_  is calculating the aoristic sum at fixed dates of temporal blocks.
Whereas, _archSeries_  calculates weights within the temporal blocks. The _archSeries_ output is also consistent with methodology and code by Crema and Palmisano. I hope the example below explain what I mean. 

I use as data example from figure 3 from [Palmisano et al, 2017](https://www.researchgate.net/publication/320347714_Comparing_archaeological_proxies_for_long-term_population_patterns_An_example_from_central_Italy)

`
library(kairos) 

dataOne = data.frame(
  id = c("a", "b", "c", "d"),
  from = c(-2200, -2000, -1600, -2000),
  to = c(-1400, -1600, -1400, -1400)
)

> aoristOne = kairos::aoristic(dataOne, step = 200, weight = TRUE)

> kairos::get_dates(aoristOne)
[1] -2200 -2000 -1800 -1600 -1400

> kairos::get_weights(aoristOne)
     [,1]      [,2]      [,3]      [,4]      [,5]
[1,] 0.25 0.2500000 0.2500000 0.2500000 0.2500000
[2,] 0.00 0.5000000 0.5000000 0.5000000 0.0000000
[3,] 0.00 0.0000000 0.0000000 1.0000000 1.0000000
[4,] 0.00 0.3333333 0.3333333 0.3333333 0.3333333

> aoristOne@.Data
         [,1]
[1,] 0.250000
[2,] 1.083333
[3,] 1.083333
[4,] 2.083333
[5,] 1.583333

`

`

library(archSeries)

dataTwo = data.frame(
  id = c("a", "b", "c", "d"),
  Start = c(-2200, -2000, -1600, -2000),
  End = c(-1400, -1600, -1400, -1400)
)

> aoristTwo = archSeries::aorist(dataTwo, bin.width = 200)
> aoristTwo
           bin bin.no    aorist
1: -2200--2000      1 0.2500000
2: -2000--1800      2 1.0833333
3: -1800--1600      3 1.0833333
4: -1600--1400      4 0.5833333

`

The _kairos_ package returned 5 aoristic sums for each date break but _archSeries_ calculated 4 sums for each temporal bin.

I would appreciate any help with understanding the method implemented in _kairos_ package. 
Especially, that the kairos::roc() function returns 4 bins for the same dataset.

**Comment by nfrerebeau** [comment]
Thanks for bringing this up! The implementation of the aoristic sum in kairos was flawed. It actually makes more sense to calculate the aoristic sum within the time blocks rather than at the break dates between blocks. I have just corrected the function which is now returning consistent results.

``` r
library(kairos)

x <- data.frame(
  id = c("a", "b", "c", "d"),
  from = c(-2200, -2000, -1600, -2000),
  to = c(-1400, -1600, -1400, -1400)
)

aorist_weighted <- aoristic(x, step = 200, weight = TRUE)
get_weights(aorist_weighted)
#> , , 1
#> 
#>      -2200_-2000 -2000_-1800 -1800_-1600 -1600_-1400
#> [1,]        0.25   0.2500000   0.2500000   0.2500000
#> [2,]        0.00   0.5000000   0.5000000   0.0000000
#> [3,]        0.00   0.0000000   0.0000000   1.0000000
#> [4,]        0.00   0.3333333   0.3333333   0.3333333

aorist_raw <- aoristic(x, step = 200, weight = FALSE)
get_weights(aorist_raw)
#> , , 1
#> 
#>      -2200_-2000 -2000_-1800 -1800_-1600 -1600_-1400
#> [1,]           1           1           1           1
#> [2,]           0           1           1           0
#> [3,]           0           0           0           1
#> [4,]           0           1           1           1
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

There was also a bug in the calculation of the aoristic sum per group, the values were counted twice. This is fixed.

The rate of change is calculated between time blocks, so there is one less value than time blocks.

**Comment by topographos** [comment]
Hi, many thanks for looking at this so promptly and fixing, again great work!
