### ISSUE TITLE
Year formats - aoristic

### ISSUE THREAD

**Issue by topographos** [tesselle/kairos#10]
Hi again,
I have only recently upgraded to v 2.1 and I am struggling to wrap a head around the years and calendar formatting.
I am trying to run aoristic function. My data are formatted in the following way where years BCE are negative e.g. -300 and years CE are positive e.g. 300. However, when I run the function (with default CE calendar) all the negative BCE dates are ignored and only time blocks from 0 onwards are returned.
I got no idea how to set the analysis for dates that span from -3300 to 700?
Any help is appreciated.

**Comment by nfrerebeau** [comment]
I can't reproduce this issue on my side. The following reprex use negative values for BCE years and it works as expected: 

```r
## Data from Husi 2022
data("loire", package = "folio")

## Get time range
loire_range <- loire[, c("lower", "upper")]

## Arbitrary offset
loire_range$lower <- loire_range$lower - mean(loire_range$lower)
loire_range$upper <- loire_range$upper - mean(loire_range$upper)
range(loire_range) # BCE years are negative
#> [1] -589.0813  885.9187

## Calculate aoristic sum (normal)
ao <- aoristic(loire_range, step = 50, calendar = CE())
plot(ao, col = "grey")
```
Could you give me more details?
